databases:
  - name: armystat
    plan: free
    databaseName: armystat
    user: armystat

services:
  - type: web
    name: armystat
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: armystat
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
