databases:
  - name: ArmyChecker
    databaseName: ArmyChecker
    user: ArmyChecker

services:
  - type: web
    name: ArmyChecker
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ArmyChecker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
